<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="10" hostname="LAPTOP-15RBTEBO" name="org.testng.demo.IretryClass" tests="12" failures="2" timestamp="2022-02-22T11:13:41 IST" time="0.090" errors="0">
  <testcase name="user1" time="0.004" classname="org.testng.demo.IretryClass">
    <failure type="java.lang.AssertionError" message="expected [b] but found [B]">
      <![CDATA[java.lang.AssertionError: expected [b] but found [B]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:863)
at org.testng.Assert.assertEquals(Assert.java:873)
at org.testng.demo.IretryClass.user1(IretryClass.java:15)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- user1 -->
  <system-out/>
  <testcase name="user" time="0.007" classname="org.testng.demo.IretryClass">
    <skipped/>
  </testcase> <!-- user -->
  <system-out/>
  <testcase name="user1" time="0.004" classname="org.testng.demo.IretryClass">
    <skipped/>
  </testcase> <!-- user1 -->
  <system-out/>
  <testcase name="user" time="0.004" classname="org.testng.demo.IretryClass">
    <failure type="java.lang.AssertionError" message="expected [a] but found [A]">
      <![CDATA[java.lang.AssertionError: expected [a] but found [A]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:863)
at org.testng.Assert.assertEquals(Assert.java:873)
at org.testng.demo.IretryClass.user(IretryClass.java:11)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- user -->
  <system-out/>
  <testcase name="user1" time="0.003" classname="org.testng.demo.IretryClass">
    <skipped/>
  </testcase> <!-- user1 -->
  <system-out/>
  <testcase name="user" time="0.009" classname="org.testng.demo.IretryClass">
    <skipped/>
  </testcase> <!-- user -->
  <system-out/>
  <testcase name="user1" time="0.010" classname="org.testng.demo.IretryClass">
    <skipped/>
  </testcase> <!-- user1 -->
  <system-out/>
  <testcase name="user1" time="0.004" classname="org.testng.demo.IretryClass">
    <skipped/>
  </testcase> <!-- user1 -->
  <system-out/>
  <testcase name="user1" time="0.006" classname="org.testng.demo.IretryClass">
    <skipped/>
  </testcase> <!-- user1 -->
  <system-out/>
  <testcase name="user" time="0.009" classname="org.testng.demo.IretryClass">
    <skipped/>
  </testcase> <!-- user -->
  <system-out/>
  <testcase name="user" time="0.022" classname="org.testng.demo.IretryClass">
    <skipped/>
  </testcase> <!-- user -->
  <system-out/>
  <testcase name="user" time="0.008" classname="org.testng.demo.IretryClass">
    <skipped/>
  </testcase> <!-- user -->
  <system-out/>
</testsuite> <!-- org.testng.demo.IretryClass -->
